2015-09-15 10:53:21 开始运行爬虫----------paipaidai---------------------------------------
2015-09-15 10:53:22+0800 [scrapy] INFO: Scrapy 0.24.4 started (bot: paipaidai)
2015-09-15 10:53:22+0800 [scrapy] INFO: Optional features available: ssl, http11, boto, django
2015-09-15 10:53:22+0800 [scrapy] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'paipaidai.spiders', 'SPIDER_MODULES': ['paipaidai.spiders'], 'BOT_NAME': 'paipaidai'}
2015-09-15 10:53:22+0800 [scrapy] INFO: Enabled extensions: LogStats, TelnetConsole, CloseSpider, WebService, CoreStats, SpiderState
2015-09-15 10:53:23+0800 [scrapy] INFO: Enabled downloader middlewares: HttpAuthMiddleware, DownloadTimeoutMiddleware, UserAgentMiddleware, RetryMiddleware, DefaultHeadersMiddleware, MetaRefreshMiddleware, HttpCompressionMiddleware, RedirectMiddleware, CookiesMiddleware, ChunkedTransferMiddleware, DownloaderStats
2015-09-15 10:53:23+0800 [scrapy] INFO: Enabled spider middlewares: HttpErrorMiddleware, OffsiteMiddleware, RefererMiddleware, UrlLengthMiddleware, DepthMiddleware
2015-09-15 10:53:24+0800 [scrapy] INFO: Enabled item pipelines: PaipaidaiPipeline
2015-09-15 10:53:24+0800 [paipaidai] INFO: Spider opened
2015-09-15 10:53:24+0800 [paipaidai] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2015-09-15 10:53:24+0800 [scrapy] DEBUG: Telnet console listening on 127.0.0.1:6023
2015-09-15 10:53:24+0800 [scrapy] DEBUG: Web service listening on 127.0.0.1:6080
2015-09-15 10:53:24+0800 [paipaidai] DEBUG: Redirecting (302) to <GET http://invest.ppdai.com/loan/list> from <GET http://www.ppdai.com/lend/12_s0_p1>
2015-09-15 10:53:26+0800 [paipaidai] DEBUG: Redirecting (302) to <GET http://invest.ppdai.com/loan/list> from <GET http://www.ppdai.com/lend/12_s0_p2>
2015-09-15 10:53:31+0800 [paipaidai] DEBUG: Redirecting (302) to <GET http://invest.ppdai.com/loan/list> from <GET http://www.ppdai.com/lend/13_s0_p1>
2015-09-15 10:53:35+0800 [paipaidai] DEBUG: Redirecting (302) to <GET http://invest.ppdai.com/loan/list> from <GET http://www.ppdai.com/lend/13_s0_p2>
2015-09-15 10:53:36+0800 [paipaidai] DEBUG: Retrying <GET http://www.ppdai.com/lend/14_s0_p2> (failed 1 times): 503 Service Unavailable
2015-09-15 10:53:38+0800 [paipaidai] DEBUG: Redirecting (302) to <GET http://invest.ppdai.com/loan/list> from <GET http://www.ppdai.com/lend/14_s0_p1>
2015-09-15 10:53:39+0800 [paipaidai] DEBUG: Retrying <GET http://www.ppdai.com/lend/8_s0_p1> (failed 1 times): 503 Service Unavailable
2015-09-15 10:53:44+0800 [paipaidai] DEBUG: Retrying <GET http://www.ppdai.com/lend/3_s0_p1> (failed 1 times): 503 Service Unavailable
2015-09-15 10:53:47+0800 [paipaidai] DEBUG: Redirecting (302) to <GET http://invest.ppdai.com/loan/list> from <GET http://www.ppdai.com/lend/8_s0_p2>
2015-09-15 10:53:50+0800 [paipaidai] DEBUG: Redirecting (302) to <GET http://invest.ppdai.com/loan/list> from <GET http://www.ppdai.com/lend/3_s0_p2>
2015-09-15 10:53:52+0800 [paipaidai] DEBUG: Redirecting (302) to <GET http://invest.ppdai.com/loan/list> from <GET http://www.ppdai.com/lend/15_s0_p1>
2015-09-15 10:53:53+0800 [paipaidai] DEBUG: Retrying <GET http://www.ppdai.com/lend/16_s0_p1> (failed 1 times): 503 Service Unavailable
2015-09-15 10:53:55+0800 [paipaidai] DEBUG: Redirecting (302) to <GET http://invest.ppdai.com/loan/list> from <GET http://www.ppdai.com/lend/15_s0_p2>
2015-09-15 10:53:59+0800 [paipaidai] DEBUG: Redirecting (302) to <GET http://invest.ppdai.com/loan/list> from <GET http://www.ppdai.com/lend/16_s0_p2>
2015-09-15 10:54:01+0800 [paipaidai] DEBUG: Crawled (200) <GET http://invest.ppdai.com/loan/list> (referer: None)
2015-09-15 10:54:04+0800 [paipaidai] DEBUG: Crawled (200) <GET http://invest.ppdai.com/loan/list> (referer: None)
2015-09-15 10:54:04+0800 [paipaidai] DEBUG: Filtered duplicate request: <GET http://www.ppdai.com/list/4187655> - no more duplicates will be shown (see DUPEFILTER_DEBUG to show all duplicates)
2015-09-15 10:54:07+0800 [paipaidai] DEBUG: Crawled (200) <GET http://invest.ppdai.com/loan/list> (referer: None)
2015-09-15 10:54:10+0800 [paipaidai] DEBUG: Crawled (200) <GET http://invest.ppdai.com/loan/list> (referer: None)
2015-09-15 10:54:12+0800 [paipaidai] DEBUG: Redirecting (302) to <GET http://invest.ppdai.com/loan/list> from <GET http://www.ppdai.com/lend/14_s0_p2>
2015-09-15 10:54:15+0800 [paipaidai] DEBUG: Crawled (200) <GET http://invest.ppdai.com/loan/list> (referer: None)
2015-09-15 10:54:18+0800 [paipaidai] DEBUG: Redirecting (302) to <GET http://invest.ppdai.com/loan/list> from <GET http://www.ppdai.com/lend/8_s0_p1>
2015-09-15 10:54:20+0800 [paipaidai] DEBUG: Redirecting (302) to <GET http://invest.ppdai.com/loan/list> from <GET http://www.ppdai.com/lend/3_s0_p1>
2015-09-15 10:54:23+0800 [paipaidai] DEBUG: Retrying <GET http://invest.ppdai.com/loan/list> (failed 1 times): 503 Service Unavailable
2015-09-15 10:54:23+0800 [paipaidai] DEBUG: Crawled (200) <GET http://invest.ppdai.com/loan/list> (referer: None)
2015-09-15 10:54:24+0800 [paipaidai] INFO: Crawled 6 pages (at 6 pages/min), scraped 0 items (at 0 items/min)
2015-09-15 10:54:25+0800 [paipaidai] DEBUG: Crawled (200) <GET http://invest.ppdai.com/loan/list> (referer: None)
2015-09-15 10:54:28+0800 [paipaidai] DEBUG: Retrying <GET http://invest.ppdai.com/loan/list> (failed 1 times): 503 Service Unavailable
2015-09-15 10:54:30+0800 [paipaidai] DEBUG: Redirecting (302) to <GET http://invest.ppdai.com/loan/list> from <GET http://www.ppdai.com/lend/16_s0_p1>
2015-09-15 10:54:32+0800 [paipaidai] DEBUG: Crawled (200) <GET http://www.ppdai.com/list/4187655> (referer: http://invest.ppdai.com/loan/list)
2015-09-15 10:54:32+0800 [paipaidai] ERROR: Spider error processing <GET http://www.ppdai.com/list/4187655>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spiders/crawl.py", line 69, in _parse_response
	    for requests_or_item in iterate_spider_output(cb_res):
	  File "/usr/scrapy/crawl/paipaidai/paipaidai/spiders/base.py", line 57, in parse_page
	    item['amount'] = sel.xpath('//dd[@id=\"listRestMoney\"]/text()').extract()[0].strip()
	exceptions.IndexError: list index out of range
	
2015-09-15 10:54:34+0800 [paipaidai] DEBUG: Crawled (200) <GET http://www.ppdai.com/list/4219869> (referer: http://invest.ppdai.com/loan/list)
2015-09-15 10:54:34+0800 [paipaidai] ERROR: Spider error processing <GET http://www.ppdai.com/list/4219869>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spiders/crawl.py", line 69, in _parse_response
	    for requests_or_item in iterate_spider_output(cb_res):
	  File "/usr/scrapy/crawl/paipaidai/paipaidai/spiders/base.py", line 57, in parse_page
	    item['amount'] = sel.xpath('//dd[@id=\"listRestMoney\"]/text()').extract()[0].strip()
	exceptions.IndexError: list index out of range
	
2015-09-15 10:54:34+0800 [paipaidai] DEBUG: Crawled (200) <GET http://invest.ppdai.com/loan/list> (referer: None)
2015-09-15 10:54:36+0800 [paipaidai] DEBUG: Crawled (200) <GET http://www.ppdai.com/list/4230241> (referer: http://invest.ppdai.com/loan/list)
2015-09-15 10:54:36+0800 [paipaidai] ERROR: Spider error processing <GET http://www.ppdai.com/list/4230241>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spiders/crawl.py", line 69, in _parse_response
	    for requests_or_item in iterate_spider_output(cb_res):
	  File "/usr/scrapy/crawl/paipaidai/paipaidai/spiders/base.py", line 57, in parse_page
	    item['amount'] = sel.xpath('//dd[@id=\"listRestMoney\"]/text()').extract()[0].strip()
	exceptions.IndexError: list index out of range
	
2015-09-15 10:54:39+0800 [paipaidai] DEBUG: Crawled (200) <GET http://www.ppdai.com/list/3970336> (referer: http://invest.ppdai.com/loan/list)
2015-09-15 10:54:39+0800 [paipaidai] ERROR: Spider error processing <GET http://www.ppdai.com/list/3970336>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spiders/crawl.py", line 69, in _parse_response
	    for requests_or_item in iterate_spider_output(cb_res):
	  File "/usr/scrapy/crawl/paipaidai/paipaidai/spiders/base.py", line 57, in parse_page
	    item['amount'] = sel.xpath('//dd[@id=\"listRestMoney\"]/text()').extract()[0].strip()
	exceptions.IndexError: list index out of range
	
2015-09-15 10:54:41+0800 [paipaidai] DEBUG: Crawled (200) <GET http://www.ppdai.com/list/4233565> (referer: http://invest.ppdai.com/loan/list)
2015-09-15 10:54:41+0800 [paipaidai] ERROR: Spider error processing <GET http://www.ppdai.com/list/4233565>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spiders/crawl.py", line 69, in _parse_response
	    for requests_or_item in iterate_spider_output(cb_res):
	  File "/usr/scrapy/crawl/paipaidai/paipaidai/spiders/base.py", line 57, in parse_page
	    item['amount'] = sel.xpath('//dd[@id=\"listRestMoney\"]/text()').extract()[0].strip()
	exceptions.IndexError: list index out of range
	
2015-09-15 10:54:43+0800 [paipaidai] DEBUG: Crawled (200) <GET http://www.ppdai.com/list/4235197> (referer: http://invest.ppdai.com/loan/list)
2015-09-15 10:54:43+0800 [paipaidai] ERROR: Spider error processing <GET http://www.ppdai.com/list/4235197>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spiders/crawl.py", line 69, in _parse_response
	    for requests_or_item in iterate_spider_output(cb_res):
	  File "/usr/scrapy/crawl/paipaidai/paipaidai/spiders/base.py", line 57, in parse_page
	    item['amount'] = sel.xpath('//dd[@id=\"listRestMoney\"]/text()').extract()[0].strip()
	exceptions.IndexError: list index out of range
	
2015-09-15 10:54:46+0800 [paipaidai] DEBUG: Crawled (200) <GET http://invest.ppdai.com/loan/list> (referer: None)
2015-09-15 10:54:48+0800 [paipaidai] DEBUG: Crawled (200) <GET http://www.ppdai.com/list/4166744> (referer: http://invest.ppdai.com/loan/list)
2015-09-15 10:54:48+0800 [paipaidai] ERROR: Spider error processing <GET http://www.ppdai.com/list/4166744>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spiders/crawl.py", line 69, in _parse_response
	    for requests_or_item in iterate_spider_output(cb_res):
	  File "/usr/scrapy/crawl/paipaidai/paipaidai/spiders/base.py", line 57, in parse_page
	    item['amount'] = sel.xpath('//dd[@id=\"listRestMoney\"]/text()').extract()[0].strip()
	exceptions.IndexError: list index out of range
	
2015-09-15 10:54:51+0800 [paipaidai] DEBUG: Crawled (200) <GET http://invest.ppdai.com/loan/list> (referer: None)
2015-09-15 10:54:56+0800 [paipaidai] DEBUG: Crawled (200) <GET http://invest.ppdai.com/loan/list> (referer: None)
2015-09-15 10:54:58+0800 [paipaidai] DEBUG: Crawled (200) <GET http://invest.ppdai.com/loan/list> (referer: None)
2015-09-15 10:54:59+0800 [paipaidai] DEBUG: Crawled (200) <GET http://www.ppdai.com/list/4229609> (referer: http://invest.ppdai.com/loan/list)
2015-09-15 10:54:59+0800 [paipaidai] ERROR: Spider error processing <GET http://www.ppdai.com/list/4229609>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spiders/crawl.py", line 69, in _parse_response
	    for requests_or_item in iterate_spider_output(cb_res):
	  File "/usr/scrapy/crawl/paipaidai/paipaidai/spiders/base.py", line 57, in parse_page
	    item['amount'] = sel.xpath('//dd[@id=\"listRestMoney\"]/text()').extract()[0].strip()
	exceptions.IndexError: list index out of range
	
2015-09-15 10:55:02+0800 [paipaidai] DEBUG: Crawled (200) <GET http://www.ppdai.com/list/4148830> (referer: http://invest.ppdai.com/loan/list)
2015-09-15 10:55:02+0800 [paipaidai] ERROR: Spider error processing <GET http://www.ppdai.com/list/4148830>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spiders/crawl.py", line 69, in _parse_response
	    for requests_or_item in iterate_spider_output(cb_res):
	  File "/usr/scrapy/crawl/paipaidai/paipaidai/spiders/base.py", line 57, in parse_page
	    item['amount'] = sel.xpath('//dd[@id=\"listRestMoney\"]/text()').extract()[0].strip()
	exceptions.IndexError: list index out of range
	
2015-09-15 10:55:04+0800 [paipaidai] DEBUG: Crawled (200) <GET http://invest.ppdai.com/loan/list> (referer: None)
2015-09-15 10:55:07+0800 [paipaidai] DEBUG: Crawled (200) <GET http://invest.ppdai.com/loan/list> (referer: None)
2015-09-15 10:55:10+0800 [paipaidai] DEBUG: Crawled (200) <GET http://www.ppdai.com/list/4230809> (referer: http://invest.ppdai.com/loan/list)
2015-09-15 10:55:10+0800 [paipaidai] ERROR: Spider error processing <GET http://www.ppdai.com/list/4230809>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 638, in _tick
	    taskObj._oneWorkUnit()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 484, in _oneWorkUnit
	    result = next(self._iterator)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 57, in <genexpr>
	    work = (callable(elem, *args, **named) for elem in iterable)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 96, in iter_errback
	    yield next(it)
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/offsite.py", line 26, in process_spider_output
	    for x in result:
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/referer.py", line 22, in <genexpr>
	    return (_set_referer(r) for r in result or ())
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/urllength.py", line 33, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spidermiddleware/depth.py", line 50, in <genexpr>
	    return (r for r in result or () if _filter(r))
	  File "/usr/local/lib/python2.7/dist-packages/scrapy/contrib/spiders/crawl.py", line 69, in _parse_response
	    for requests_or_item in iterate_spider_output(cb_res):
	  File "/usr/scrapy/crawl/paipaidai/paipaidai/spiders/base.py", line 57, in parse_page
	    item['amount'] = sel.xpath('//dd[@id=\"listRestMoney\"]/text()').extract()[0].strip()
	exceptions.IndexError: list index out of range
	
2015-09-15 10:55:10+0800 [paipaidai] INFO: Closing spider (finished)
2015-09-15 10:55:10+0800 [paipaidai] INFO: Dumping Scrapy stats:
	{'downloader/request_bytes': 11218,
	 'downloader/request_count': 44,
	 'downloader/request_method_count/GET': 44,
	 'downloader/response_bytes': 220338,
	 'downloader/response_count': 44,
	 'downloader/response_status_count/200': 24,
	 'downloader/response_status_count/302': 14,
	 'downloader/response_status_count/503': 6,
	 'dupefilter/filtered': 130,
	 'finish_reason': 'finished',
	 'finish_time': datetime.datetime(2015, 9, 15, 2, 55, 10, 26335),
	 'log_count/DEBUG': 47,
	 'log_count/ERROR': 10,
	 'log_count/INFO': 8,
	 'request_depth_max': 1,
	 'response_received_count': 24,
	 'scheduler/dequeued': 44,
	 'scheduler/dequeued/memory': 44,
	 'scheduler/enqueued': 44,
	 'scheduler/enqueued/memory': 44,
	 'spider_exceptions/IndexError': 10,
	 'start_time': datetime.datetime(2015, 9, 15, 2, 53, 24, 9949)}
2015-09-15 10:55:10+0800 [paipaidai] INFO: Spider closed (finished)
2015-09-15 10:55:20 爬取结束-------------paipaidai---------------------------------------
